name: Publish package to PyPi

on:
  push:
    tags:
      - '*'

jobs:

  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Install Dependencies
        run: pip install setuptools wheel

      - name: Build package
        run: echo github.ref
